### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by pinetree408** [junhwi/jwt-example#4]
- [x] JWT Section 채우기
- [x] vulnerability of JWT에 빠진 테이블 넣기
    - 테이블의 경우 latex로 테이블을 다시 그리시던가 아니면 다른데서 테이블을 그려오셔서 figure로 넣으셔도 좋을 것 같습니다.
- [x] Abstract 채우기
    - 제안하는 내용 flow (한글 버전)
        1. 요즘에 TBA(token based...)는 정말 많이 쓰인다.
        2. TBA는 기존의 SBA(server based...)의 단점등을 많이 보완한다.
        3. 그런데 리포트 되는 이슈들을 보면 아직 security 관점에서 덜 성숙했다.
        4. 그래서 우리는 TBA 중에서 사용성이 제일 높은 JWT를 바탕으로 TBA의 문제점에 대하여 알아보았다.
            - JWT를 지원하는 다양한 언어의 라이브러리를 분석하는 필드 스터디를 진행했고, 문제점을 진단했다.
        5. 우리는 이런한 문제점들을 카테고라이즈하고 실제로 공격 시나리오를 만들어 공격해보았다.
        6. 이러한 필드 스터디와 공격 시나리오등을 기반으로 JWT를 잘 사용하는 구체적인 시나리오를 제시했다.
        7. 최종적으로 우리는 필드 스터디를 통해서 JWT의 security 이슈를 진단했고, 그를 기반으로 JWT를 잘 사용할 수 있는 구체적인 시나리오를 디스커스한다.
- [ ] 다시 쭉 읽어보면서 대소문자 오탈자를 비롯한 잡다한것 체크
- [x] Method 파트는 저희 논문에서는 크게 의미가 없을 듯합니다. 두분이 보시고 필요하시면 넣고 아니면 지워주세요

**Comment by pinetree408** [comment]
@junhwi @byou-kaist 이슈 업데이트 했습니다.

**Comment by byou-kaist** [comment]
1.3 section 마지막 단락 중 "This handy debugger and library chart shows the support for JSON Web Tokens." 에 해당되는 그림이 들어가야 합니다.
